apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "zookeeper.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - name: client
      port: {{ int .Values.service.port }}
      targetPort: client
    {{- if and ( .Values.prometheus.jmx.enabled ) ( .Values.servicemonitor.enabled ) }}
    - name: jmx-prometheus
      port: {{ int .Values.prometheus.jmx.port }}
      targetPort: jmx-prometheus
    {{- end }}
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
